spring.application.name=keepia

# データベースの接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/keepia
spring.datasource.username=postgres
spring.datasource.password=${KEEPIA_DB_PASSWORD}
##spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.validate-migration-naming=true