spring.application.name=keepia

# データベースの接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/keepia
spring.datasource.username=postgres
spring.datasource.password=rootadmin
spring.datasource.driver-class-name=org.postgresql.Driver