
CREATE TABLE tenants (
	id UUID PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE'
		CHECK (status IN ('ACTIVE', 'STOPPED')),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0)
);

